// Generated by gencpp from file rtabmap_ros/CleanupLocalGrids.msg
// DO NOT EDIT!


#ifndef RTABMAP_ROS_MESSAGE_CLEANUPLOCALGRIDS_H
#define RTABMAP_ROS_MESSAGE_CLEANUPLOCALGRIDS_H

#include <ros/service_traits.h>


#include <rtabmap_ros/CleanupLocalGridsRequest.h>
#include <rtabmap_ros/CleanupLocalGridsResponse.h>


namespace rtabmap_ros
{

struct CleanupLocalGrids
{

typedef CleanupLocalGridsRequest Request;
typedef CleanupLocalGridsResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct CleanupLocalGrids
} // namespace rtabmap_ros


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::rtabmap_ros::CleanupLocalGrids > {
  static const char* value()
  {
    return "9b90cbbb6fac56a143df9416b6e1fa37";
  }

  static const char* value(const ::rtabmap_ros::CleanupLocalGrids&) { return value(); }
};

template<>
struct DataType< ::rtabmap_ros::CleanupLocalGrids > {
  static const char* value()
  {
    return "rtabmap_ros/CleanupLocalGrids";
  }

  static const char* value(const ::rtabmap_ros::CleanupLocalGrids&) { return value(); }
};


// service_traits::MD5Sum< ::rtabmap_ros::CleanupLocalGridsRequest> should match
// service_traits::MD5Sum< ::rtabmap_ros::CleanupLocalGrids >
template<>
struct MD5Sum< ::rtabmap_ros::CleanupLocalGridsRequest>
{
  static const char* value()
  {
    return MD5Sum< ::rtabmap_ros::CleanupLocalGrids >::value();
  }
  static const char* value(const ::rtabmap_ros::CleanupLocalGridsRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::rtabmap_ros::CleanupLocalGridsRequest> should match
// service_traits::DataType< ::rtabmap_ros::CleanupLocalGrids >
template<>
struct DataType< ::rtabmap_ros::CleanupLocalGridsRequest>
{
  static const char* value()
  {
    return DataType< ::rtabmap_ros::CleanupLocalGrids >::value();
  }
  static const char* value(const ::rtabmap_ros::CleanupLocalGridsRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::rtabmap_ros::CleanupLocalGridsResponse> should match
// service_traits::MD5Sum< ::rtabmap_ros::CleanupLocalGrids >
template<>
struct MD5Sum< ::rtabmap_ros::CleanupLocalGridsResponse>
{
  static const char* value()
  {
    return MD5Sum< ::rtabmap_ros::CleanupLocalGrids >::value();
  }
  static const char* value(const ::rtabmap_ros::CleanupLocalGridsResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::rtabmap_ros::CleanupLocalGridsResponse> should match
// service_traits::DataType< ::rtabmap_ros::CleanupLocalGrids >
template<>
struct DataType< ::rtabmap_ros::CleanupLocalGridsResponse>
{
  static const char* value()
  {
    return DataType< ::rtabmap_ros::CleanupLocalGrids >::value();
  }
  static const char* value(const ::rtabmap_ros::CleanupLocalGridsResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // RTABMAP_ROS_MESSAGE_CLEANUPLOCALGRIDS_H
