// Generated by gencpp from file rtabmap_ros/DetectMoreLoopClosures.msg
// DO NOT EDIT!


#ifndef RTABMAP_ROS_MESSAGE_DETECTMORELOOPCLOSURES_H
#define RTABMAP_ROS_MESSAGE_DETECTMORELOOPCLOSURES_H

#include <ros/service_traits.h>


#include <rtabmap_ros/DetectMoreLoopClosuresRequest.h>
#include <rtabmap_ros/DetectMoreLoopClosuresResponse.h>


namespace rtabmap_ros
{

struct DetectMoreLoopClosures
{

typedef DetectMoreLoopClosuresRequest Request;
typedef DetectMoreLoopClosuresResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct DetectMoreLoopClosures
} // namespace rtabmap_ros


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::rtabmap_ros::DetectMoreLoopClosures > {
  static const char* value()
  {
    return "4d201f0476beb2d12b70b64edae8edab";
  }

  static const char* value(const ::rtabmap_ros::DetectMoreLoopClosures&) { return value(); }
};

template<>
struct DataType< ::rtabmap_ros::DetectMoreLoopClosures > {
  static const char* value()
  {
    return "rtabmap_ros/DetectMoreLoopClosures";
  }

  static const char* value(const ::rtabmap_ros::DetectMoreLoopClosures&) { return value(); }
};


// service_traits::MD5Sum< ::rtabmap_ros::DetectMoreLoopClosuresRequest> should match
// service_traits::MD5Sum< ::rtabmap_ros::DetectMoreLoopClosures >
template<>
struct MD5Sum< ::rtabmap_ros::DetectMoreLoopClosuresRequest>
{
  static const char* value()
  {
    return MD5Sum< ::rtabmap_ros::DetectMoreLoopClosures >::value();
  }
  static const char* value(const ::rtabmap_ros::DetectMoreLoopClosuresRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::rtabmap_ros::DetectMoreLoopClosuresRequest> should match
// service_traits::DataType< ::rtabmap_ros::DetectMoreLoopClosures >
template<>
struct DataType< ::rtabmap_ros::DetectMoreLoopClosuresRequest>
{
  static const char* value()
  {
    return DataType< ::rtabmap_ros::DetectMoreLoopClosures >::value();
  }
  static const char* value(const ::rtabmap_ros::DetectMoreLoopClosuresRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::rtabmap_ros::DetectMoreLoopClosuresResponse> should match
// service_traits::MD5Sum< ::rtabmap_ros::DetectMoreLoopClosures >
template<>
struct MD5Sum< ::rtabmap_ros::DetectMoreLoopClosuresResponse>
{
  static const char* value()
  {
    return MD5Sum< ::rtabmap_ros::DetectMoreLoopClosures >::value();
  }
  static const char* value(const ::rtabmap_ros::DetectMoreLoopClosuresResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::rtabmap_ros::DetectMoreLoopClosuresResponse> should match
// service_traits::DataType< ::rtabmap_ros::DetectMoreLoopClosures >
template<>
struct DataType< ::rtabmap_ros::DetectMoreLoopClosuresResponse>
{
  static const char* value()
  {
    return DataType< ::rtabmap_ros::DetectMoreLoopClosures >::value();
  }
  static const char* value(const ::rtabmap_ros::DetectMoreLoopClosuresResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // RTABMAP_ROS_MESSAGE_DETECTMORELOOPCLOSURES_H
