// Generated by gencpp from file rtabmap_ros/GlobalBundleAdjustment.msg
// DO NOT EDIT!


#ifndef RTABMAP_ROS_MESSAGE_GLOBALBUNDLEADJUSTMENT_H
#define RTABMAP_ROS_MESSAGE_GLOBALBUNDLEADJUSTMENT_H

#include <ros/service_traits.h>


#include <rtabmap_ros/GlobalBundleAdjustmentRequest.h>
#include <rtabmap_ros/GlobalBundleAdjustmentResponse.h>


namespace rtabmap_ros
{

struct GlobalBundleAdjustment
{

typedef GlobalBundleAdjustmentRequest Request;
typedef GlobalBundleAdjustmentResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct GlobalBundleAdjustment
} // namespace rtabmap_ros


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::rtabmap_ros::GlobalBundleAdjustment > {
  static const char* value()
  {
    return "2e1ed640ba9f481fdaa2226734d70674";
  }

  static const char* value(const ::rtabmap_ros::GlobalBundleAdjustment&) { return value(); }
};

template<>
struct DataType< ::rtabmap_ros::GlobalBundleAdjustment > {
  static const char* value()
  {
    return "rtabmap_ros/GlobalBundleAdjustment";
  }

  static const char* value(const ::rtabmap_ros::GlobalBundleAdjustment&) { return value(); }
};


// service_traits::MD5Sum< ::rtabmap_ros::GlobalBundleAdjustmentRequest> should match
// service_traits::MD5Sum< ::rtabmap_ros::GlobalBundleAdjustment >
template<>
struct MD5Sum< ::rtabmap_ros::GlobalBundleAdjustmentRequest>
{
  static const char* value()
  {
    return MD5Sum< ::rtabmap_ros::GlobalBundleAdjustment >::value();
  }
  static const char* value(const ::rtabmap_ros::GlobalBundleAdjustmentRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::rtabmap_ros::GlobalBundleAdjustmentRequest> should match
// service_traits::DataType< ::rtabmap_ros::GlobalBundleAdjustment >
template<>
struct DataType< ::rtabmap_ros::GlobalBundleAdjustmentRequest>
{
  static const char* value()
  {
    return DataType< ::rtabmap_ros::GlobalBundleAdjustment >::value();
  }
  static const char* value(const ::rtabmap_ros::GlobalBundleAdjustmentRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::rtabmap_ros::GlobalBundleAdjustmentResponse> should match
// service_traits::MD5Sum< ::rtabmap_ros::GlobalBundleAdjustment >
template<>
struct MD5Sum< ::rtabmap_ros::GlobalBundleAdjustmentResponse>
{
  static const char* value()
  {
    return MD5Sum< ::rtabmap_ros::GlobalBundleAdjustment >::value();
  }
  static const char* value(const ::rtabmap_ros::GlobalBundleAdjustmentResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::rtabmap_ros::GlobalBundleAdjustmentResponse> should match
// service_traits::DataType< ::rtabmap_ros::GlobalBundleAdjustment >
template<>
struct DataType< ::rtabmap_ros::GlobalBundleAdjustmentResponse>
{
  static const char* value()
  {
    return DataType< ::rtabmap_ros::GlobalBundleAdjustment >::value();
  }
  static const char* value(const ::rtabmap_ros::GlobalBundleAdjustmentResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // RTABMAP_ROS_MESSAGE_GLOBALBUNDLEADJUSTMENT_H
