// Generated by gencpp from file rtabmap_ros/LoadDatabase.msg
// DO NOT EDIT!


#ifndef RTABMAP_ROS_MESSAGE_LOADDATABASE_H
#define RTABMAP_ROS_MESSAGE_LOADDATABASE_H

#include <ros/service_traits.h>


#include <rtabmap_ros/LoadDatabaseRequest.h>
#include <rtabmap_ros/LoadDatabaseResponse.h>


namespace rtabmap_ros
{

struct LoadDatabase
{

typedef LoadDatabaseRequest Request;
typedef LoadDatabaseResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct LoadDatabase
} // namespace rtabmap_ros


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::rtabmap_ros::LoadDatabase > {
  static const char* value()
  {
    return "686abf12c0ee22118c7e5fcc29bcdabe";
  }

  static const char* value(const ::rtabmap_ros::LoadDatabase&) { return value(); }
};

template<>
struct DataType< ::rtabmap_ros::LoadDatabase > {
  static const char* value()
  {
    return "rtabmap_ros/LoadDatabase";
  }

  static const char* value(const ::rtabmap_ros::LoadDatabase&) { return value(); }
};


// service_traits::MD5Sum< ::rtabmap_ros::LoadDatabaseRequest> should match
// service_traits::MD5Sum< ::rtabmap_ros::LoadDatabase >
template<>
struct MD5Sum< ::rtabmap_ros::LoadDatabaseRequest>
{
  static const char* value()
  {
    return MD5Sum< ::rtabmap_ros::LoadDatabase >::value();
  }
  static const char* value(const ::rtabmap_ros::LoadDatabaseRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::rtabmap_ros::LoadDatabaseRequest> should match
// service_traits::DataType< ::rtabmap_ros::LoadDatabase >
template<>
struct DataType< ::rtabmap_ros::LoadDatabaseRequest>
{
  static const char* value()
  {
    return DataType< ::rtabmap_ros::LoadDatabase >::value();
  }
  static const char* value(const ::rtabmap_ros::LoadDatabaseRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::rtabmap_ros::LoadDatabaseResponse> should match
// service_traits::MD5Sum< ::rtabmap_ros::LoadDatabase >
template<>
struct MD5Sum< ::rtabmap_ros::LoadDatabaseResponse>
{
  static const char* value()
  {
    return MD5Sum< ::rtabmap_ros::LoadDatabase >::value();
  }
  static const char* value(const ::rtabmap_ros::LoadDatabaseResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::rtabmap_ros::LoadDatabaseResponse> should match
// service_traits::DataType< ::rtabmap_ros::LoadDatabase >
template<>
struct DataType< ::rtabmap_ros::LoadDatabaseResponse>
{
  static const char* value()
  {
    return DataType< ::rtabmap_ros::LoadDatabase >::value();
  }
  static const char* value(const ::rtabmap_ros::LoadDatabaseResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // RTABMAP_ROS_MESSAGE_LOADDATABASE_H
