// Generated by gencpp from file rtabmap_ros/RemoveLabel.msg
// DO NOT EDIT!


#ifndef RTABMAP_ROS_MESSAGE_REMOVELABEL_H
#define RTABMAP_ROS_MESSAGE_REMOVELABEL_H

#include <ros/service_traits.h>


#include <rtabmap_ros/RemoveLabelRequest.h>
#include <rtabmap_ros/RemoveLabelResponse.h>


namespace rtabmap_ros
{

struct RemoveLabel
{

typedef RemoveLabelRequest Request;
typedef RemoveLabelResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct RemoveLabel
} // namespace rtabmap_ros


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::rtabmap_ros::RemoveLabel > {
  static const char* value()
  {
    return "ea23f97416b04c6151d2b576c0665ac1";
  }

  static const char* value(const ::rtabmap_ros::RemoveLabel&) { return value(); }
};

template<>
struct DataType< ::rtabmap_ros::RemoveLabel > {
  static const char* value()
  {
    return "rtabmap_ros/RemoveLabel";
  }

  static const char* value(const ::rtabmap_ros::RemoveLabel&) { return value(); }
};


// service_traits::MD5Sum< ::rtabmap_ros::RemoveLabelRequest> should match
// service_traits::MD5Sum< ::rtabmap_ros::RemoveLabel >
template<>
struct MD5Sum< ::rtabmap_ros::RemoveLabelRequest>
{
  static const char* value()
  {
    return MD5Sum< ::rtabmap_ros::RemoveLabel >::value();
  }
  static const char* value(const ::rtabmap_ros::RemoveLabelRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::rtabmap_ros::RemoveLabelRequest> should match
// service_traits::DataType< ::rtabmap_ros::RemoveLabel >
template<>
struct DataType< ::rtabmap_ros::RemoveLabelRequest>
{
  static const char* value()
  {
    return DataType< ::rtabmap_ros::RemoveLabel >::value();
  }
  static const char* value(const ::rtabmap_ros::RemoveLabelRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::rtabmap_ros::RemoveLabelResponse> should match
// service_traits::MD5Sum< ::rtabmap_ros::RemoveLabel >
template<>
struct MD5Sum< ::rtabmap_ros::RemoveLabelResponse>
{
  static const char* value()
  {
    return MD5Sum< ::rtabmap_ros::RemoveLabel >::value();
  }
  static const char* value(const ::rtabmap_ros::RemoveLabelResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::rtabmap_ros::RemoveLabelResponse> should match
// service_traits::DataType< ::rtabmap_ros::RemoveLabel >
template<>
struct DataType< ::rtabmap_ros::RemoveLabelResponse>
{
  static const char* value()
  {
    return DataType< ::rtabmap_ros::RemoveLabel >::value();
  }
  static const char* value(const ::rtabmap_ros::RemoveLabelResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // RTABMAP_ROS_MESSAGE_REMOVELABEL_H
